### ISSUE TITLE
Movable menu items

### ISSUE THREAD

**Issue by ezeiger92** [ezeiger92/QuestWorld2#33]
Add a way to move categories, quests around.

**Comment by ezeiger92** [comment]
Requires new progress file format:
```YAML
missions:
  <mission_uuid>: ~

quests:
  <quest_uuid>: ~
```
